apiVersion: apps/v1
kind: Deployment
metadata:
  name: junosapp
spec:
  selector:
    matchLabels:
      app: junosapp
  template:
    metadata:
      labels:
        app: junosapp
    spec:
      containers:
      - name: junosapp
        image: juniormj/junosapp:1.1
        env:
          - name: USER_DB
            value: "******"
          - name: PASS_DB
            value: "********"
          - name: SERV_DB
            value: "xxx.xx.xxx.xx"
        ports:
        - containerPort: 15000
      imagePullSecrets:
        - name: regcred
