apiVersion: v1
kind: Service
metadata:
  name: junosapp
spec:
  selector:
    app: junosapp
  type: LoadBalancer
  ports:
  - port: 15000 # porta do computador (bate nessa porta)
    targetPort: 15000  # porta do pod
    nodePort: 30000 # porta do serviço
